-- Multi-store (multi-tenant) foundation.
--
-- Turns a single-store schema into a platform: one `stores` row per business,
-- every content row owned by exactly one store, and RLS that scopes each admin
-- to the store(s) they belong to.
--
-- Fashion Factory Nepal is migrated in as the default store, with its existing
-- products, categories and branches attached to it. Nothing is lost: the
-- singleton `store_settings` row is copied into `stores` before that table is
-- dropped, in this same transaction.
--
-- Deployment model: ONE codebase, one build per store. The storefront reads
-- committed JSON generated by scripts/generate-site-data.mjs, which takes a
-- STORE_SLUG and emits that store's data. Adding a store is a row here plus a
-- deployment pointed at that slug — never a fork of the application.

-- ---------------------------------------------------------------------------
-- Stores
-- ---------------------------------------------------------------------------

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),

  -- Identity. `slug` is the tenant key used by STORE_SLUG at publish time, so
  -- it has to stay URL- and env-var-safe.
  slug text not null unique
    constraint stores_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null,
  legal_name text,
  tagline text,
  description text,

  -- Brand assets. URLs rather than uploads so a store can point at anything
  -- public (its own storage folder, a CDN, an existing site).
  logo_url text,
  favicon_url text,

  -- Contact. phone is stored as dialled; whatsapp_number is digits-only with
  -- country code, because wa.me rejects anything else — the same split the
  -- storefront's telHref/whatsappHref helpers expect.
  phone text not null,
  whatsapp_number text not null
    constraint stores_whatsapp_digits check (whatsapp_number ~ '^\d{6,15}$'),
  email text,

  -- Social. Handle and URL are stored separately: the handle is displayed
  -- verbatim (it may be styled, e.g. "Fashionfactory@99") while the URL is what
  -- is actually linked, so the site never has to guess one from the other.
  instagram_handle text,
  instagram_url text,
  tiktok_handle text,
  tiktok_url text,
  facebook_url text,

  -- Place and hours. `opening_hours` is the human string shown on the site;
  -- `business_hours` is the structured form for schema.org and future
  -- open/closed logic, e.g. [{"days":["Mo","Tu"],"opens":"09:00","closes":"17:00"}].
  location_label text not null,
  address text,
  country_code text not null default 'NP',
  currency text not null default 'NPR',
  opening_hours text not null,
  business_hours jsonb not null default '[]'::jsonb,

  -- Presentation and capability toggles, kept as jsonb so a new theme token or
  -- feature flag does not need a migration on every store's behalf. Shapes are
  -- documented and validated in the application layer (src/models).
  branding jsonb not null default '{}'::jsonb,
  features jsonb not null default '{}'::jsonb,

  -- Storefront copy that names specific places, so it cannot be a literal in
  -- the page. A newline inside visit_title becomes a line break in the heading.
  visit_title text,
  visit_step_body text,

  -- Search metadata. Explicit rather than derived from name + tagline: the
  -- title tag and keyword set are the store's own SEO decisions, and a
  -- generated approximation would quietly replace them.
  seo_title text,
  seo_description text,
  seo_keywords text[] not null default '{}',

  site_url text,

  is_active boolean not null default true,
  is_default boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- At most one default store. A partial unique index rather than a check
-- constraint, because the rule is across rows, not within one.
create unique index if not exists stores_one_default_idx
  on public.stores ((is_default)) where is_default;

create index if not exists stores_active_idx on public.stores (is_active);

alter table public.stores enable row level security;

-- ---------------------------------------------------------------------------
-- Seed / migrate the first store
-- ---------------------------------------------------------------------------
-- Carries the live singleton across when this runs on an existing project, and
-- falls back to Fashion Factory's known details on a fresh one. Either way the
-- result is exactly one default store, so the NOT NULL backfills below have
-- something to point at.

do $$
declare
  -- Fashion Factory's known details, used verbatim on a fresh project and
  -- overwritten field by field when a live store_settings row exists. Scalars
  -- rather than a record variable: reading into a record only works if the
  -- legacy table is actually there, and an unassigned record cannot be
  -- dereferenced at all.
  v_name             text := 'Fashion Factory Nepal';
  v_phone            text := '+977 9840260456';
  v_whatsapp         text := '9779840260456';
  v_ig_handle        text := '@fashion.factory_2022';
  v_ig_url           text := 'https://www.instagram.com/fashion.factory_2022/';
  v_location_label   text := 'Kathmandu Valley, Nepal · Kirtipur & Budhanilkantha';
  v_opening_hours    text := '9:00 AM – 5:00 PM daily';
begin
  if exists (select 1 from public.stores where is_default) then
    return;
  end if;

  if to_regclass('public.store_settings') is not null then
    execute $q$
      select coalesce(name, $1), coalesce(phone, $2), coalesce(whatsapp_number, $3),
             coalesce(instagram_handle, $4), coalesce(instagram_url, $5),
             coalesce(location_label, $6), coalesce(opening_hours, $7)
      from public.store_settings limit 1
    $q$
    into v_name, v_phone, v_whatsapp, v_ig_handle, v_ig_url, v_location_label, v_opening_hours
    using v_name, v_phone, v_whatsapp, v_ig_handle, v_ig_url, v_location_label, v_opening_hours;
  end if;

  insert into public.stores (
    slug, name, tagline, description,
    phone, whatsapp_number,
    instagram_handle, instagram_url, tiktok_handle, tiktok_url,
    location_label, opening_hours, business_hours,
    visit_title, visit_step_body,
    branding, features,
    seo_title, seo_description, seo_keywords,
    is_default
  ) values (
    'fashion-factory-nepal',
    v_name,
    'Define Your Style.',
    'Fashion Factory is a Kathmandu-based fashion and clothing retail destination. Browse the collection, connect with the store, and visit in person to find your next look.',
    v_phone,
    v_whatsapp,
    v_ig_handle,
    v_ig_url,
    'Fashionfactory@99',
    'https://www.tiktok.com/@fashionfactory99',
    v_location_label,
    v_opening_hours,
    '[{"days":["Mo","Tu","We","Th","Fr","Sa","Su"],"opens":"09:00","closes":"17:00"}]'::jsonb,
    E'Two doors in the\nKathmandu Valley.',
    'Come to Kirtipur or Budhanilkantha and try it on.',
    '{"accent":"#8b3f35","accentDeep":"#6d2f27","accentLight":"#d98a76","ink":"#14120f","paper":"#f2ede3","wordmark":["FASHION","FACTORY","NEPAL"]}'::jsonb,
    '{"styleQuiz":true,"instagramFeed":true,"testimonials":true,"faqs":true,"contactForm":true,"locations":true}'::jsonb,
    'Fashion Factory Nepal | Fashion Store in Kathmandu',
    'Discover fashion at Fashion Factory Nepal. Browse the collection, contact the store, and get directions to our Kirtipur and Budhanilkantha branches.',
    array['Fashion Factory Nepal','fashion store Kathmandu','clothing store Kathmandu','fashion shop Kathmandu','Fashion Factory Kirtipur','Fashion Factory Budhanilkantha'],
    true
  );
end $$;

-- ---------------------------------------------------------------------------
-- Attach existing content to a store
-- ---------------------------------------------------------------------------

alter table public.products add column if not exists store_id uuid references public.stores(id) on delete cascade;
alter table public.categories add column if not exists store_id uuid references public.stores(id) on delete cascade;
alter table public.store_locations add column if not exists store_id uuid references public.stores(id) on delete cascade;

update public.products       set store_id = (select id from public.stores where is_default) where store_id is null;
update public.categories     set store_id = (select id from public.stores where is_default) where store_id is null;
update public.store_locations set store_id = (select id from public.stores where is_default) where store_id is null;

alter table public.products       alter column store_id set not null;
alter table public.categories     alter column store_id set not null;
alter table public.store_locations alter column store_id set not null;

-- ---------------------------------------------------------------------------
-- Keys: identifiers are unique per store, not globally
-- ---------------------------------------------------------------------------
-- Two stores must both be able to have a category called "new" and a product
-- slugged "everyday-overshirt". That means the tenant column belongs in every
-- key, and products must reference a category *of their own store* — enforced
-- by a composite foreign key, not by application code.

alter table public.products drop constraint if exists products_category_id_fkey;

alter table public.categories drop constraint if exists categories_slug_key;
alter table public.categories drop constraint if exists categories_pkey;
alter table public.categories add constraint categories_pkey primary key (store_id, id);
alter table public.categories add constraint categories_store_slug_key unique (store_id, slug);

alter table public.products
  add constraint products_category_fkey
  foreign key (store_id, category_id) references public.categories (store_id, id)
  on update cascade on delete restrict;

alter table public.products drop constraint if exists products_slug_key;
alter table public.products add constraint products_store_slug_key unique (store_id, slug);

alter table public.store_locations drop constraint if exists store_locations_pkey;
alter table public.store_locations add constraint store_locations_pkey primary key (store_id, id);

-- Read paths are always store-scoped now, so the indexes lead with store_id.
drop index if exists public.products_visible_sort_idx;
drop index if exists public.products_sort_order_idx;
drop index if exists public.categories_sort_idx;
create index if not exists products_store_visible_sort_idx on public.products (store_id, is_visible, sort_order);
create index if not exists categories_store_active_sort_idx on public.categories (store_id, active, sort_order);
create index if not exists store_locations_store_active_sort_idx on public.store_locations (store_id, active, sort_order);

-- ---------------------------------------------------------------------------
-- Admin scoping
-- ---------------------------------------------------------------------------
-- An admin row with store_id = null is a platform admin (every store). A row
-- with a store_id administers exactly that store. A person can hold several
-- rows, so the primary key widens from user_id to (user_id, store_id) — with a
-- unique index standing in for the null half, since NULL is not comparable in a
-- primary key.

alter table public.admin_users add column if not exists store_id uuid references public.stores(id) on delete cascade;

alter table public.admin_users drop constraint if exists admin_users_pkey;
create unique index if not exists admin_users_user_store_idx
  on public.admin_users (user_id, store_id) where store_id is not null;
create unique index if not exists admin_users_platform_idx
  on public.admin_users (user_id) where store_id is null;
create index if not exists admin_users_store_idx on public.admin_users (store_id);

-- Existing admins predate tenancy, so they become platform admins — which is
-- what they effectively were.

-- SECURITY DEFINER for the same reason as private.is_admin(): a policy must be
-- able to read admin_users without recursing into admin_users' own policies.
create or replace function private.is_platform_admin()
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid()) and a.store_id is null
  );
$$;

create or replace function private.can_manage_store(target_store uuid)
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (
    select 1 from public.admin_users a
    where a.user_id = (select auth.uid())
      and (a.store_id is null or a.store_id = target_store)
  );
$$;

-- Storage keys product images under <store-slug>/<uuid>.webp, so the write
-- policies need slug -> store resolution.
create or replace function private.can_manage_store_slug(target_slug text)
returns boolean language sql security definer stable set search_path = '' as $$
  select exists (
    select 1
    from public.admin_users a
    left join public.stores s on s.slug = target_slug
    where a.user_id = (select auth.uid())
      and (a.store_id is null or a.store_id = s.id)
  );
$$;

revoke all on function private.is_platform_admin() from public;
revoke all on function private.can_manage_store(uuid) from public;
revoke all on function private.can_manage_store_slug(text) from public;
grant execute on function private.is_platform_admin() to authenticated;
grant execute on function private.can_manage_store(uuid) to authenticated;
grant execute on function private.can_manage_store_slug(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Policies
-- ---------------------------------------------------------------------------
-- Public reads stay open on published catalogue and contact data — that is the
-- storefront's whole purpose — but every write is now scoped to the store the
-- row belongs to. An admin of store A can no longer touch store B's rows even
-- with a valid session and a direct REST call.

drop policy if exists "anon can read visible products" on public.products;
drop policy if exists "admins can read all products" on public.products;
drop policy if exists "admins can insert products" on public.products;
drop policy if exists "admins can update products" on public.products;
drop policy if exists "admins can delete products" on public.products;

create policy "public can read visible products" on public.products
  for select to anon, authenticated
  using (is_visible = true and exists (select 1 from public.stores s where s.id = store_id and s.is_active));
create policy "store admins read products" on public.products
  for select to authenticated using (private.can_manage_store(store_id));
create policy "store admins insert products" on public.products
  for insert to authenticated with check (private.can_manage_store(store_id));
create policy "store admins update products" on public.products
  for update to authenticated using (private.can_manage_store(store_id)) with check (private.can_manage_store(store_id));
create policy "store admins delete products" on public.products
  for delete to authenticated using (private.can_manage_store(store_id));

drop policy if exists "anon can read active categories" on public.categories;
drop policy if exists "admins manage categories" on public.categories;
create policy "public can read active categories" on public.categories
  for select to anon, authenticated using (active = true);
create policy "store admins manage categories" on public.categories
  for all to authenticated using (private.can_manage_store(store_id)) with check (private.can_manage_store(store_id));

drop policy if exists "anon can read active locations" on public.store_locations;
drop policy if exists "admins manage locations" on public.store_locations;
create policy "public can read active locations" on public.store_locations
  for select to anon, authenticated using (active = true);
create policy "store admins manage locations" on public.store_locations
  for all to authenticated using (private.can_manage_store(store_id)) with check (private.can_manage_store(store_id));

-- Store profiles are public read (name, hours and contact details are published
-- on the storefront anyway) but only their own admins may edit them, and only a
-- platform admin may create or remove a store — onboarding is deliberately not
-- a self-serve operation.
create policy "public can read active stores" on public.stores
  for select to anon, authenticated using (is_active or private.can_manage_store(id));
create policy "store admins update their store" on public.stores
  for update to authenticated using (private.can_manage_store(id)) with check (private.can_manage_store(id));
create policy "platform admins create stores" on public.stores
  for insert to authenticated with check (private.is_platform_admin());
create policy "platform admins delete stores" on public.stores
  for delete to authenticated using (private.is_platform_admin());

-- admin_users stays readable only to admins, and writable through SQL /
-- service_role only, so the web host never needs a privileged key to manage
-- membership.
drop policy if exists "admins can read admin list" on public.admin_users;
create policy "admins read their admin list" on public.admin_users
  for select to authenticated
  using (private.is_platform_admin() or private.can_manage_store(store_id));

-- ---------------------------------------------------------------------------
-- Storage: per-store folders
-- ---------------------------------------------------------------------------

drop policy if exists "admins can upload product images" on storage.objects;
drop policy if exists "admins can update product images" on storage.objects;
drop policy if exists "admins can delete product images" on storage.objects;

create policy "store admins upload product images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and private.can_manage_store_slug((storage.foldername(name))[1]));
create policy "store admins update product images" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images' and private.can_manage_store_slug((storage.foldername(name))[1]))
  with check (bucket_id = 'product-images' and private.can_manage_store_slug((storage.foldername(name))[1]));
create policy "store admins delete product images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images' and private.can_manage_store_slug((storage.foldername(name))[1]));

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

drop trigger if exists stores_touch_updated_at on public.stores;
create trigger stores_touch_updated_at before insert or update on public.stores
  for each row execute function private.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Retire the singleton
-- ---------------------------------------------------------------------------
-- Its contents were copied into public.stores at the top of this migration, and
-- the application now reads stores exclusively. Leaving it in place would give
-- the storefront two disagreeing sources for the same contact details.

drop table if exists public.store_settings;
